from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from uuid import uuid4


class Env(Enum):
    """Bayse API environment."""

    PRODUCTION = "production"
    SANDBOX = "sandbox"


_ENV_BASE_URLS: dict[Env, str] = {
    Env.PRODUCTION: "https://relay.bayse.markets",
    Env.SANDBOX: "https://sandbox.relay.bayse.markets",
}


def base_url_for(env: Env) -> str:
    """Resolve the base URL for a given environment."""
    url = _ENV_BASE_URLS.get(env)
    if url is None:
        raise ValueError(f"Unknown environment: {env}")
    return url


@dataclass
class TraceConfig:
    """Configuration for request trace IDs.

    Trace IDs are auto-generated as ``{session_id}-{seq:06d}``.
    They can be overridden per-call via the ``trace_id`` parameter on any method.
    """

    session_id: str = field(default_factory=lambda: uuid4().hex[:12])
    """Prefix for all trace IDs generated by this client instance."""

    start_sequence: int = 1
    """Starting sequence number for this client. Typically left at 1."""


@dataclass
class RetryConfig:
    """Configuration for automatic request retries."""

    max_retries: int = 5
    """Maximum number of retry attempts before raising. Set to 0 to disable retries."""

    base_delay: float = 1.0
    """Base delay in seconds for the exponential backoff."""

    max_delay: float = 60.0
    """Maximum delay in seconds between retries."""

    jitter: float = 0.1
    """Fixed jitter added to each delay: ``delay += random(0, jitter)``."""

    retry_on_statuses: tuple[int, ...] = (429, 500, 502, 503, 504)
    """HTTP status codes that trigger a retry on safe or idempotent requests."""

    retry_unsafe_on_statuses: tuple[int, ...] = (429,)
    """HTTP status codes that trigger a retry on non-idempotent requests.

    Deliberately narrower than :attr:`retry_on_statuses`. A ``502`` or ``504`` on a
    ``POST`` may mean the upstream *did* process the request, so replaying it risks a
    duplicate order. ``429`` is included because the Bayse rate limiter rejects
    over-budget requests before they reach the matching engine, so a rate-limited write
    never touched anything and is safe to replay.

    Set to ``()`` to disable retries on non-idempotent requests entirely.
    """

    safe_methods: frozenset[str] = frozenset({"GET", "HEAD", "OPTIONS"})
    """HTTP methods with no side effects. Always eligible for :attr:`retry_on_statuses`."""

    idempotent_methods: frozenset[str] = frozenset({"PUT", "DELETE"})
    """HTTP methods that are idempotent by specification.

    Replaying these is expected to be a no-op — re-cancelling an already-cancelled
    order returns an error rather than cancelling a second one. Treated the same as
    :attr:`safe_methods` for retry purposes.
    """


@dataclass
class ClientConfig:
    """Top-level configuration for a ``BayseClient`` instance."""

    public_key: str
    """The ``pk_*`` public API key."""

    secret_key: str
    """The ``sk_*`` secret API key."""

    env: Env = Env.PRODUCTION
    """Target environment."""

    trace: TraceConfig = field(default_factory=TraceConfig)
    """Trace ID configuration."""

    retry: RetryConfig = field(default_factory=RetryConfig)
    """Retry configuration."""

    timeout: float = 30.0
    """Default HTTP request timeout in seconds."""
